version: '3.8'
services:
  xor:
    container_name: xor-full-archive
    image: ethereum/client-go:v1.12.0
    restart: always
    working_dir: /xor
    hostname: xor-full-archive
    volumes:
      - $PWD:/xor
    ports:
      - 30456:30456
      - 8545:8545
      - 8546:8546
    command: |
      --networkid 1123581321
      --syncmode "full"
      --gcmode "archive"
      --datadir "datadir"
      --port 30456
      --bootnodes "enode://e2ae9505eaa95ad184a7e4b46f977bedd5e8df2b8a6896fe4354dda649bd13bf59099a394bee44b330d4c65ab677a3da4f7def52ecd42f4d3c0d63ae800d38d3@176.9.34.155:30456"
      --http --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --http.api "eth,net,web3,txpool,clique"
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.origins "*" --ws.api "net,web3,eth"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "1"